### ISSUE TITLE
Vega-Lite 5.7 schema is released as 5.6.1

### ISSUE THREAD

**Issue by binste** [vega/schema#8]
I think the 5.7 schema got mistakenly released as 5.6.1 with the [latest commit](https://github.com/vega/schema/commit/0d1d25395a15ee79ff74dbb147283248faafa869) in this repo. CC @domoritz. In any case, thank you very much for your work on 5.7!

**Comment by domoritz** [comment]
😔 I'll look into what's happening.

**Comment by domoritz** [comment]
The release somehow picked up the wrong version. 

<img width="571" alt="Screenshot 2023-04-15 at 10 01 56" src="https://user-images.githubusercontent.com/589034/232229112-f19efbb5-3359-4e6a-9fa8-0629b967d0ad.png">

**Comment by domoritz** [comment]
I think the issue was that I didn't push to main before creating the release. It's for a silly reason that has to do with some broken ssh on my machine. I triggered a new build and that hopefully fixes it.

**Comment by domoritz** [comment]
That worked: https://github.com/vega/schema/commit/3c4ee823527156040d70ad86f708a5ac3c769c11. I'll manually reset the previous schema.

**Comment by binste** [comment]
Great, thank you very much for the quick fix and in general for prioritising the blocking issues for Altair!
